### ISSUE TITLE
pistache not building correctly

### ISSUE THREAD

**Issue by peggy0135** [irods/irods_client_rest_cpp#9] opened 2021-01-22 01:33 UTC
OS: ubuntu18.04
comands:
1.mkdir build
2.cd build/
3.cmake build ../
4.make package

while I build with the command "make package", I got the error below,
but not sure about the problem with pistache (I can build the pistache from their github site, but I can't built from the "externals")

```
Scanning dependencies of target irods_client_rest_cpp_zonereport_server
[  2%] Building CXX object CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/ZoneReportApiMainServer.cpp.o
[  4%] Building CXX object CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/model/ModelBase.cpp.o
[  6%] Building CXX object CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/model/Query_results.cpp.o
[  8%] Building CXX object CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/api/ZoneReportApi.cpp.o
[ 10%] Building CXX object CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/impl/ZoneReportApiImpl.cpp.o
[ 12%] Linking CXX executable irods_client_rest_cpp_zonereport_server
/usr/bin/ld: /usr/local/lib/libpistache.a(http.cc.o): undefined reference to symbol '_ZNSt15basic_streambufIcSt11char_traitsIcEE7seekoffElSt12_Ios_SeekdirSt13_Ios_Openmode@@GLIBCXX_3.4'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/build.make:203: recipe for target 'irods_client_rest_cpp_zonereport_server' failed
make[2]: *** [irods_client_rest_cpp_zonereport_server] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/all' failed
make[1]: *** [CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```
Is there any idea that I can figure out this problem.

Thank you

**Comment by trel** [comment] 2021-01-22 02:04
You mention you cannot build pistache from externals - I expect that is related here...

What is the problem with building pistache in externals (on the 4-2-stable branch)?

**Comment by peggy0135** [comment] 2021-01-22 02:49
I follow the instruction in README, there was no error message while "make pistache" and "make install".
But if I just didn't see the pistache in "/opt/irods-externals".

**Comment by trel** [comment] 2021-01-22 03:02
Ah, okay...

If pistache built correctly, you should then have a `.deb` that you can install via `dpkg -i` - then the files would be placed in `/opt/irods-externals/`.

**Comment by peggy0135** [comment] 2021-01-22 03:16
do you mean a file named "irods-externals-pistache0.0.2-0_1.0~bionic_amd64.deb" in external dir?
Then how about the tar files and shell script in "~/externals/pistache0.0.2-0_src/pistache/build"?

**Comment by trel** [comment] 2021-01-22 03:21
yes, you install that `.deb` and the compiled parts you need will be available to the rest of the irods software (in this case, this rest cpp client).

if there are additional parts of the `build/` that you need, we can create an issue in the externals repository.

**Comment by peggy0135** [comment] 2021-01-22 04:05
while I install the .deb file
it shows,

dpkg-deb: error: 'irods-externals-pistache0.0.2-0_1.0~bionic_amd64.deb' is not a Debian format archive
dpkg: error processing archive irods-externals-pistache0.0.2-0_1.0~bionic_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 irods-externals-pistache0.0.2-0_1.0~bionic_amd64.deb

**Comment by trel** [comment] 2021-01-22 05:01
i have reproduced that error - sorry about that.

appears the binaries are not where they should be - and so the package is empty.

will look into that ASAP.

**Comment by peggy0135** [comment] 2021-01-22 05:11
Thank you for your help,
also happened to the packages:
 irods-externals-cpython2.7-0_1.0~bionic_amd64.deb
 irods-externals-pistache0.0.2-0_1.0~bionic_amd64.deb
 irods-externals-qpid0.34-2_1.0~bionic_amd64.deb
 irods-externals-qpid-proton0.23.0-0_1.0~bionic_amd64.deb

Thank you

**Comment by trel** [comment] 2021-01-23 23:43
both master (https://github.com/irods/externals/commit/1fac187270c017502f1c8c63572db9e07bf2897a) and 4-2-stable (https://github.com/irods/externals/commit/24057ce7a2e4b27f4122a2e2cf86e36fc3f1f805) of pistache in irods/externals should build as expected.

now working to get the rest_cpp building...

**Comment by peggy0135** [comment] 2021-01-24 16:21
sorry, I tried to build it (with a re-installed ubuntu18.04) and still not work,
output:
[  2%] Building CXX object CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/ZoneReportApiMainServer.cpp.o
/home/qct/irods_client_rest_cpp/ZoneReportApiMainServer.cpp:13:10: fatal error: 'pistache/endpoint.h'
      file not found
#include "pistache/endpoint.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/build.make:62: recipe for target 'CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/ZoneReportApiMainServer.cpp.o' failed
make[2]: *** [CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/ZoneReportApiMainServer.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/all' failed
make[1]: *** [CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

but this time, I saw the pistache appeared in the /opt/irods-exteranls directory

**Comment by trel** [comment] 2021-01-24 16:27
Yes, please try with the changes in https://github.com/irods/irods_client_rest_cpp/pull/10

I haven't merged it yet - confirmation there would be great.

**Comment by trel** [comment] 2021-01-25 04:38
have merged the fixes here - everything should build and install now.

please also remember this is not released yet - so we appreciate any/all feedback.

**Comment by peggy0135** [comment] 2021-01-25 04:52
sorry, it still showed
[  2%] Building CXX object CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/ZoneReportApiMainServer.cpp.o
/root/irods_client_rest_cpp/ZoneReportApiMainServer.cpp:13:10: fatal error: 'pistache/endpoint.h' file not found
#include "pistache/endpoint.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/build.make:62: recipe for target 'CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/ZoneReportApiMainServer.cpp.o' failed
make[2]: *** [CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/ZoneReportApiMainServer.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/all' failed
make[1]: *** [CMakeFiles/irods_client_rest_cpp_zonereport_server.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by trel** [comment] 2021-01-25 05:01
if you've got the latest tip of 4-2-stable (dc4770e)... it should find the pistache files in `/opt/irods-externals/`

**Comment by peggy0135** [comment] 2021-01-25 08:33
ok, now I successfully installed the package and checked the status of irods_client_rest_cpp (active)
but when I tried to get the auth token, "curl" showed me:
root@irods-ubuntu:~# export TOKEN=$(curl -X POST "http://localhost:80/irods-rest/1.0.0/auth?user_name=rods&password=rods&auth_type=native")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused

and I checked with "netstat" but nothing listening on 80 port

so should I also need to install "nginx"?

**Comment by trel** [comment] 2021-01-25 13:04
consider the version number - try 0.1.0?

**Comment by peggy0135** [comment] 2021-01-26 00:25
by the way when I check out the monitoring tool more than 90% of memory (totally 8GB) has been occupied even the server has been staying idle.
Is that normal? because when I check out with "top", irods-server occupied the most memory.

**Comment by trel** [comment] 2021-01-26 00:36
I'm not sure about the memory consumption - more information is welcome, but I expect this is premature before you get things working as expected.

Since the project is now building and installed, can we close this issue?

I expect the 404 problem above is due to an nginx reverse proxy configuration issue.

**Comment by peggy0135** [comment] 2021-01-26 00:54
so the package is working depend on the nginx server?
because after I install the nginx server, there wasn't any process listening on port 80.
Thank you

**Comment by trel** [comment] 2021-01-26 01:32
have you done the configuration described in https://github.com/irods/irods_client_rest_cpp#configuring-the-service ?

**Comment by peggy0135** [comment] 2021-01-26 01:34
sorry I copy the file to the wrong place
I will try it

**Comment by trel** [comment] 2021-03-09 19:15
closing - pistache is built and integrated as designed.

**Closed by trel** 2021-03-09 19:15 UTC
Labels: bug
